# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

orbs:
  win: circleci/windows@2.2.0 # The Windows orb give you everything you need to start using the Windows executor.

jobs:
  build_windows:
    executor:
      name: win/default
      shell: bash.exe
    steps:
      - checkout
      - run: curl https://files.jrsoftware.org/is/6/innosetup-6.2.0.exe > innosetup.exe
      - run:
          command: ./innosetup.exe /VERYQUIET /ALLUSERS
          shell: powershell.exe
      - run: git submodule update --init --recursive
      - run: CI= (cd gephgui-wry/gephgui && npm ci && npm run build)
      # - run: bash sync-binaries.sh
      # - run: bash build-windows.sh
      # - run: sudo apt install python3-pip
      # - run: sudo pip3 install --upgrade b2
      # - run: b2 authorize-account $B2_KEYID $B2_APPKEY
      # - run: b2 upload-file ./dist/*.exe b2://geph-dl/STAGING/

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  sample: # This is the name of the workflow, feel free to change it to better match your workflow.
    # Inside the workflow, you define the jobs you want to run.
    jobs:
      - build_windows:
          context:
            - master
